### ISSUE TITLE
[stalktoy] Fatal error: unknown column 'ipb_reason'

### ISSUE THREAD

**Issue by Jeff-Gdot** [Pathoschild/Wikimedia-contrib#122]
While browsing https://tools.wmflabs.org/meta/stalktoy/113.210.97.113

Could not perform query:
SQL: [286] SELECT ipb_by_text, ipb_address, ipb_reason, DATE_FORMAT(ipb_timestamp, "%Y-%b-%d") AS timestamp, DATE_FORMAT(ipb_expiry, "%Y-%b-%d") AS expiry, ipb_anon_only FROM ipblocks WHERE (ipb_range_start <= ? AND ipb_range_end >= ?) OR (ipb_range_start >= ? AND ipb_range_end <= ?) /*d25eca61*/ Sent SQL: [322] SELECT ipb_by_text, ipb_address, ipb_reason, DATE_FORMAT(ipb_timestamp, "%Y-%b-%d") AS timestamp, DATE_FORMAT(ipb_expiry, "%Y-%b-%d") AS expiry, ipb_anon_only FROM ipblocks WHERE (ipb_range_start <= '71D26171' AND ipb_range_end >= '71D26171') OR (ipb_range_start >= '71D26171' AND ipb_range_end <= '71D26171') /*d25eca61*/ Params: 4 Key: Position #0: paramno=0 name=[0] "" is_param=1 param_type=2 Key: Position #1: paramno=1 name=[0] "" is_param=1 param_type=2 Key: Position #2: paramno=2 name=[0] "" is_param=1 param_type=2 Key: Position #3: paramno=3 name=[0] "" is_param=1 param_type=2 
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ipb_reason' in 'field list'

Fatal error: Uncaught Error: Call to a member function fetchAllAssoc() on boolean in /data/project/meta/git/wikimedia-contrib/tool-labs/stalktoy/framework/StalktoyEngine.php:334 Stack trace: #0 /data/project/meta/git/wikimedia-contrib/tool-labs/stalktoy/index.php(90): StalktoyEngine->getLocalIPBlocks(Object(Stalktoy\GlobalIP)) #1 {main} thrown in /data/project/meta/git/wikimedia-contrib/tool-labs/stalktoy/framework/StalktoyEngine.php on line 334

**Comment by Pathoschild** [comment]
Fixed and deployed. Apparently some columns are being removed as part of [T166732](https://phabricator.wikimedia.org/T166732). The `globalblocks.gb_reason_id` column doesn't exist yet, but I updated the code for the others. Let me know if you notice any issues!

**Comment by Pathoschild** [comment]
I reverted the update, since referencing the `comment` table caused slowdowns and high CPU usage (possibly an issue with the Toolforge view?). The error should still be gone, since they undid the migration on eswiki.

We have [until March 19th](https://lists.wikimedia.org/pipermail/cloud/2019-March/000569.html) to update.

**Comment by Pathoschild** [comment]
I disabled the fields removed in the comment refactor. If no performance issues come up, I'll migrate AccountEligibility first (since the fields are required for it to work correctly in some case) and watch for performance issues, then do Stalktoy next (since the fields are just shown in the UI for that one).

**Comment by Pathoschild** [comment]
All tools are now migrated.
