### ISSUE TITLE
[Stewardry] Does not load

### ISSUE THREAD

**Issue by revi** [Pathoschild/Wikimedia-contrib#127]
```
Timezone: Asia/Seoul Date: 2019-06-11
22:31:56 <+revi> anyone else: does https://tools.wmflabs.org/meta/stewardry/hywiki load for you?
(snip)
22:36:05 <sDrewth> and no it isn't successfully loading for me
22:37:01 <cohaf> nope not working for me too
22:37:13 <+hauskatze> not working revi 
```

[Stewardry/hywiki](https://tools.wmflabs.org/meta/stewardry/hywiki) is not loading at all. If it was just me it was my network borking but 4 connections simultaneously failing to load mean it is dead.

/CC @MarcoAurelioWM

**Comment by Pathoschild** [comment]
Fixed by restarting the web service. It may have been related to the recent Toolforge issues (e.g. [T222978](https://phabricator.wikimedia.org/T222978), [T225391](https://phabricator.wikimedia.org/T225391), and [performance issues related to the comment/actor changes](https://lists.wikimedia.org/pipermail/cloud/2019-June/000716.html)). Thanks for reporting it!
