### ISSUE TITLE
Update tools for new `toolforge.org` domain

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#139]
Due to the introduction of the `toolforge.org` domain (_See_ [News/Toolforge.org](https://wikitech.wikimedia.org/wiki/News/Toolforge.org), [[Cloud] Toolforge: new domain toolforge.org](https://lists.wikimedia.org/pipermail/cloud/2020-May/001079.html) and [Task T234617](https://phabricator.wikimedia.org/T234617) we should make sure all tools are ready to work with the new `$tool.toolforge.org` domain. The [News/Toolforge.org](https://wikitech.wikimedia.org/wiki/News/Toolforge.org) page on Wikitech should have the required info/steps to achieve this. Thanks!

**Comment by Pathoschild** [comment]
See [related Phabricator ticket](https://phabricator.wikimedia.org/T247432) re interwiki links.

**Comment by Pathoschild** [comment]
The `meta` project is now migrated and using `--canonical`.

Migrating `crossactivity` will take a bit more work due to what seems to be a Toolforge bug: if you have a folder under `public_html` that matches the account name, Toolforge requires it to appear twice in the path even when using the new domain (i.e. `X.toolforge.org/X/X` instead of the expected `X.toolforge.org/X`). I'm reworking how the tools are split to address that.

**Comment by Pathoschild** [comment]
All tools are migrated and using `--canonical`.

Crossactivity is now at [meta2.toolforge.org](https://meta2.toolforge.org), with an identical URL structure to the main [meta.toolforge.org](https://meta.toolforge.org). They redirect as needed, so it's safe to access any tool through either host and all previous URLs should still work.

Let me know if you notice any issues!

**Comment by szc126** [comment]
Within the last hour or so, I noticed that `https://tools-static.wmflabs.org/meta/scripts/pathoschild.templatescript.js` returns "404 Not Found" not found now. Does this happen for you as well?

**Comment by Pathoschild** [comment]
@szc126 Yep, that should be fixed now. Thanks for reporting it!
