### ISSUE TITLE
TemplateScript causes "Blocked loading mixed active content" error on Firefox

### ISSUE THREAD

**Issue by he7d3r** [Pathoschild/Wikimedia-contrib#50]
I'm getting this in the console (the message is in Portuguese):
Bloqueado carregamento de conteúdo ativo mesclado
“http://tools-static.wmflabs.org/meta/scripts/pathoschild.templatescript.js?_=1427549606013

**Comment by Pathoschild** [comment]
Hello @he7d3r. Thanks for reporting the issue; I fixed a redirect to HTTP when fetching an old tool path, so that error won't happen anymore.

Seeing that error does indicate you're calling the script in an outdated way in [your global.js](https://meta.wikimedia.org/wiki/User:He7d3r/global.js). I would normally update it for you, but your scripts are in a custom minified format. I suggest updating your two script references based on [the current setup instructions](https://meta.wikimedia.org/wiki/TemplateScript#Installation).

**Comment by he7d3r** [comment]
I fixed it here: https://github.com/he7d3r/mw-gadget-TemplateScript/commit/547b51a1799721a12d68e3279bd00f65a4761c6a

**Comment by Pathoschild** [comment]
There's one old reference left under 'BookTools'; could you update that one too?

**Comment by Pathoschild** [comment]
@he7d3r There's one old reference left under 'BookTools'; could you update that one too?

**Comment by he7d3r** [comment]
@Pathoschild done in https://github.com/he7d3r/mw-gadget-BookTools/commit/a5cfb8c8e4e2dcd0eb9005b40fbfea3c1482eb96

**Comment by Pathoschild** [comment]
Thanks!
