### ISSUE TITLE
[regex editor] add session plugins for custom use cases

### ISSUE THREAD

**Issue by he7d3r** [Pathoschild/Wikimedia-contrib#57]
Instead of [writting to localStorage](https://github.com/Pathoschild/Wikimedia-contrib/blob/master/user-scripts/pathoschild.regexeditor.js#L158-L159), the regex tool could store its values to a `userjs-something`, in case the user is logged in. This would make them more permanent than it currently is (e.g. work across multiple browsers).

You can get the saved preferences using
https://meta.wikimedia.org/w/api.php?action=query&meta=userinfo&uiprop=options
and set the new values using

``` javascript
mw.loader.using( [ 'mediawiki.api.options' ] )
.done( function () {
    // See https://gerrit.wikimedia.org/r/#/c/160308/
    new mw.Api().saveOptions(
        { "userjs-tsre-sessions": "..." }
    )
    .done(...);
} );
```

For anonymous users, it could fallback to localStorage.

**Comment by Pathoschild** [comment]
That's a good idea. Is there an equivalent method to fetch options? I don't see one [in the documentation](https://doc.wikimedia.org/mediawiki-core/master/js/#!/api/mw.Api.plugin.options).

**Comment by he7d3r** [comment]
Oh, actually, we can use this:
```javascript
mw.loader.using( [ 'user.options' ] )
.done( function () {
    var xyz = mw.user.options.get( "userjs-tsre-sessions" );
    //...
} );
```

**Comment by alexbrollo** [comment]
localStorage id good for me, but while writing a it.source similar tool ("memoRegex") we choosed to store data into Index talk page, so that sessions can be used/updated by any user. Three scripts allow to download,  to upload and to read by javascript from any related Page ("align") data; bolder users can edit too manually data when needed. We use Index talk page as a storage location, since we are going to use Index tal page as the place for any work-specific suggestion/help for reviewers. An example here: //it.wikisource.org/wiki/Discussioni_indice:Caterina_da_Siena_-_Epistole,_1.djvu

**Comment by alexbrollo** [comment]
Another difference between memoRegex and Regex editor is that regex aren't saved as a list, but as a dictionary, the key being the regex itself; the advantage is that an updated code for a stored regex overwrites quietly  the old one.

**Comment by Pathoschild** [comment]
@alexbrollo That's a really interesting idea, but probably too specialised to support by default. We could maybe use a plugin approach to support specialised use cases like this. Maybe something like this?

```javascript
pathoschild.regexEditor.addSessionStore('index-page', {
    read: function() { ... },     // return a list of sessions
    write: function(session) { }, // show a modal saying "go to <x page> to edit this session"?
    savesAny: false               // store will only be called to save its own sessions
});
```

Then we'd just add two default `savesAny` plugins for localStorage and user preferences. Would that work for you?

**Comment by alexbrollo** [comment]
I added a picture to my profile just to make clear the difference in age between us - and the related obviuos difference in understanding speed.... :-) . Give me the needed, long time to understand and test all details of templateScript, then I'll comment your suggestion.

**Comment by alexbrollo** [comment]
Ok, as an exercise to see if I'm understandig anything I'll try to write routines to store localStorage data into a default page, and to upload  data from the the page into localStorage. A question: when precisely Regex Editor reads  localStorage data? Does it read localStorage once when running Editor the first time while editing a page, or does it read again data any time the box is opened while editing the same page?

**Comment by Pathoschild** [comment]
It reads from localStorage each time the editor is shown (so if you close and reopen the editor, it'll read from it again). It also reads from localStorage each time you save or delete a session, but that may change if we take the plugin approach (since we can't assume reading from storage is trivial anymore).

**Comment by alexbrollo** [comment]
It's very comfortable behaviour for me, since - just as a test - I'll write  external script uploading and downloading permanently stored data into/from localStorage and sessions will be refreshed while editing the page. I'll store sessions into a public space so that they can be uploaded and used by any user; the idea of storing them into personal preferences is excellent if you want personal data, but I would like to share them among editors of the same book, even if them don't know Regex syntax.

**Comment by Pathoschild** [comment]
This has veered off from the original topic, so I created #59 for the original issue (saving sessions to user preferences).

**Comment by Pathoschild** [comment]
I sketched out a few approaches that handle the use cases described above, and settled on the concept of session generator plugins. (You can skip to the bottom if you don't care about why.)

### ✘ generic storage plugins
In theory the best solution is to use generic plugins, in which even the default `localstorage` behaviour is just a plugin. In practice, making storage generic is complex so it's probably not the approach we should adopt.

(You can skip the rest of this section if you don't care about the details.)

Let's start with a few requirements. A plugin can...
* fetch sessions (from localstorage, user preferences, a shared subpage, or something else);
* _optionally_ save and delete sessions (e.g. a user shouldn't save his personal sessions into a shared subpage);
* be enabled conditionally (e.g. `localstorage` is only available in a compatible browser, and `shared-subpage` is only available if there's a subpage for the current work).

Here's the plugin interface that meets these requirements:

```javascript
/**
 * Represents a plugin which persists sessions.
 * @property {string} key The unique key which identifies this sessions store.
 * @property {boolean} enabled Whether this store is available in the current context.
 * @property {number} priority This plugin's priority when deciding which store to save patterns into. If several plugins have the highest priority, sessions will be added to all of them. The priority for default plugins is 1.
 * @class
 */
self.SessionStore = {
	key: null,
	enabled: null,
	priority: 1,

	/**
	 * Fetch the available sessions.
	 * @returns {Session[]} The available sessions.
	 */
	getAll: null,

	/**
	 * Save a session (or null for a readonly plugin). If the key is already in use, it should update the existing session.
	 * @param {Session} session The session to save.
	 */
	save: null,

	/**
	 * Delete a session (or null for a readonly plugin).
	 * @param {Session} session The session to delete.
	 */
	delete: null
};
```

Since some plugins aren't writable, that means you can read a session from one plugin, make changes, and save it to a different plugin. Asking the user which plugin to use would be confusing — most users don't know or care about the underlying storage mechanism.

That suggests two concepts:
* **session stickiness:** we'll always save the session back to the same plugin it was read from, if possible.
* **plugin priority:** if we can't save changes to the original plugin, we'll choose the writable plugin with the highest priority. For example, we'll try saving to `userpreferences` before we fallback to `localstorage`.

While that works fine with the default plugins, adding custom plugins into the mix introduces a huge number of edge cases:
* What if multiple plugins have the same priority — do we duplicate the session to all of them, or arbitrarily choose one of them?
* What if your session is stored in a plugin that's only available in specific cases?
* What if the plugin implements `save` but not `delete`?
* What if a plugin is unmaintained — does the regex editor eventually break for those users?
* Some sessions will be saved globally, some locally, and some conditionally depending on the plugin. Will that be confusing to the user?
* How does the UI communicate the fact that sessions come from different plugins with different capabilities (some readonly, some undeleteable, etc) without being confusing or cluttered?
* etc.

Although this approach would be very powerful, it would also be difficult to maintain (especially if we actually did develop many custom plugins) and confusing to the user.

### ✓ session generator plugins
In practice, session generator plugins solve the same use cases in a much simpler way. The core library is responsible for storing the user's saved sessions, but custom plugins can generate template sessions the user can use.

For example, let's look at @alexbrollo's use case. A subpage like `[[Index:Caterina da Siena.djvu/regexeditor.js]]` stores some common patterns that are useful for that work, and the wiki has a `subpage` plugin that reads them. When editing a page in that work, users see some readonly template sessions (gray) alongside their personal sessions (blue):
![image](https://cloud.githubusercontent.com/assets/230581/9425866/109f7998-48f0-11e5-99d6-d84bfa89ee67.png)

If they load one of the generated sessions and make some changes, they see a message like this:
> _You have unsaved changes to a readonly session from [Index:Caterina da Siena.djvu/regexeditor.js](#). Click 'save' below to save them as a new session in your account._

The plugins can't control where or how sessions are stored (that's the core library's responsibility). However plugins aren't necessarily tied to a storage mechanism at all — they're free to generate sessions dynamically. For example, they could add a "clean up OCR errors" session only if they detect OCR errors on the current page.

@alexbrollo: would this solve your use case?

**Comment by alexbrollo** [comment]
You are largely overestimating my skills.... but yes, my aim is to share
useful sessions among any user that is working about the same work, and
saving sessions into a standard subpage is what I need. IMHO talk pages are
better than base pages, since they don't waste statistics and extractions,
from current practice Index talk page turned out as the best location for
shared regex data.

I never feel the need of more than one session, since in our practice
sessions are strictly related to one work - to one Index page; I always
used such sessions into nsPage only, to standardize both text fixing and -
much more useful - standard  formatting, into header and footer too. See a
recent  example here:
https://wikisource.org/wiki/Index_talk:No_turco_napolitano.djvu

Alex




2015-08-23 0:17 GMT+02:00 Jesse Plamondon-Willard <notifications@github.com>
:

**Comment by Pathoschild** [comment]
I'm no longer very active on Wikimedia wikis, so I'm not actively developing new features for these scripts. (I'm still maintaining the existing scripts though.) I'll close this as _won't do_, but pull requests are welcome if someone wanted to tackle this.
