### ISSUE TITLE
[AccountEligibility] [URGENT] Add support for candidates/voters on the 2018 Steward Elections

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#96]
I've just noticed that nobody asked you to create the new forms for this year [elections](https://meta.wikimedia.org/wiki/Stewards/Elections_2018/Guidelines). Is it possible to have it done? Candidate submissions start at 00:00 15 January 2018 (UTC). Thanks!

**Comment by Pathoschild** [comment]
I'm travelling without access to a computer today, but I'll set it up as soon as I can (should be before 5am UTC).

**Comment by Pathoschild** [comment]
@MarcoAurelioWM The code changes are ready (see #97), but I won't be able to deploy until I reach home. The ETA is 6am UTC, but there are a lot of airplane delays due to local weather.

Here are the specific rules to confirm:
* Voters:
  * not a bot on any wiki;
  * 600 edits across all wikis before 01 November 2017;
  * 50 edits across all wikis between 01 August 2017 and 31 January 2018 inclusively.
* Candidates:
  * same rules as voters;
  * held the sysop flag on any one wiki for at least 90 days before 02 February 2018 at 14:00 UTC.

Let me know if you want to make any changes.

**Comment by MarcoAurelioWM** [comment]
Hello. Yes, those are the requirements for this year election. Thanks.
-- 
M. A.

**Comment by Pathoschild** [comment]
Deployed!
